In [2]:
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException,ElementNotInteractableException
import requests
import re

Q1.Scrape the details of most viewed videos on YouTube from Wikipedia:
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos/
You need to find following details:

A) Rank

B) Name

C) Artist

D) Upload date

E) Views

In [3]:
driver=driver = webdriver.Chrome(r'C:\Users\hp\Downloads\chromedriver_win32\chromedriver.exe')
time.sleep(2)

url = "https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos"
driver.get(url)

time.sleep(2)
name=[]
try:
    names=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[2]")
    for i in names:
        name.append(i.text)
except NoSuchElementException:
    name.append('No details available')
except StaleElementReferenceException:
    name.append('No details available')
    
time.sleep(2)    
rank=[]
try:
    ranks=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[1]")
    for i in ranks:
        rank.append(i.text)
except NoSuchElementException:
    rank.append('No details available')
except StaleElementReferenceException:
    rank.append('No details available')

time.sleep(2)
artist=[]
try:
    artists=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[3]")
    for i in artists:
        artist.append(i.text)
except NoSuchElementException:
    artist.append('No details available')
except StaleElementReferenceException:
    artist.append('No details available')
    
time.sleep(2)    
views=[]
try:
    views_list=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[4]")
    for i in views_list:
        views.append(i.text)
except NoSuchElementException:
    views.append('No details available')
except StaleElementReferenceException:
    views.append('No details available')
    
time.sleep(2)    
upload_date=[]
try:
    upload_date_list=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[5]")
    for i in upload_date_list:
        upload_date.append(i.text)
except NoSuchElementException:
    upload_date.append('No details available')
except StaleElementReferenceException:
    upload_date.append('No details available')
    
time.sleep(2)    
df=pd.DataFrame({"Rank":rank,
                 "Name":name,
                "Uploader/artist":artist,
                "Date of upload":upload_date,
                "Views(in billion)":views})
df

<ipython-input-3-6eea1ae5ee2c>:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=driver = webdriver.Chrome(r'C:\Users\hp\Downloads\chromedriver_win32\chromedriver.exe')
C:\Users\hp\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py:502: UserWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  warnings.warn("find_elements_by_* commands are deprecated. Please use find_elements() instead")

,Rank,Name,Uploader/artist,Date of upload,Views(in billion)
0,1,"""Baby Shark Dance""[23]",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016","9,453,134,982"
1,2,"""Despacito""[25]",Luis Fonsi,"January 12, 2017","7,572,747,360"
2,3,"""Johny Johny Yes Papa""[26]",LooLoo Kids,"October 8, 2016","5,781,348,353"
3,4,"""Shape of You""[27]",Ed Sheeran,"January 30, 2017","5,483,427,541"
4,5,"""See You Again""[28]",Wiz Khalifa,"April 6, 2015","5,284,905,560"
5,6,"""Bath Song""[31]",Cocomelon – Nursery Rhymes,"May 2, 2018","4,549,294,432"
6,7,"""Learning Colors – Colorful Eggs on a Farm""[32]",Miroshka TV,"February 27, 2018","4,513,879,675 (as of Sep 29, 2021)"
7,8,"""Masha and the Bear – Recipe for Disaster""[33]",Get Movies,"January 31, 2012","4,461,096,975"
8,9,"""Uptown Funk""[34]",Mark Ronson,"November 19, 2014","4,319,159,452"
9,10,"""Phonics Song with Two Words""[35]",ChuChu TV,"March 6, 2014","4,220,180,419"
10,11,"""Gangnam Style""[36]",Psy,"July 15, 2012","4,211,421,413"
11,12,"""Dame Tu Cosita""[38]",El Chombo,"April 5, 2018","3,633,337,215"
12,13,"""Sugar""[39]",Maroon 5,"January 14, 2015","3,565,906,701"
13,14,"""Sorry""[40]",Justin Bieber,"October 22, 2015","3,474,094,697"
14,15,"""Roar""[41]",Katy Perry,"September 5, 2013","3,444,786,615"
15,16,"""Counting Stars""[42]",OneRepublic,"May 31, 2013","3,412,577,920"
16,17,"""Thinking Out Loud""[43]",Ed Sheeran,"October 7, 2014","3,337,279,340"
17,18,"""Wheels on the Bus""[44]",Cocomelon – Nursery Rhymes,"May 24, 2018","3,291,808,512"
18,19,"""Dark Horse""[45]",Katy Perry,"February 20, 2014","3,155,611,442"
19,20,"""Faded""[46]",Alan Walker,"December 3, 2015","3,155,489,927"
20,21,"""Girls Like You""[47]",Maroon 5,"May 31, 2018","3,143,116,042"
21,22,"""Lean On""[48]",Major Lazer,"March 22, 2015","3,105,926,931"
22,23,"""Bailando""[49]",Enrique Iglesias,"April 11, 2014","3,105,539,316"
23,24,"""Shake It Off""[50]",Taylor Swift,"August 18, 2014","3,104,230,107"
24,25,"""Let Her Go""[51]",Passenger,"July 25, 2012","3,090,217,295"
25,26,"""Axel F""[52]",Crazy Frog,"June 17, 2009","3,035,828,739"
26,27,"""Mi Gente""[53]",J Balvin,"June 29, 2017","2,986,493,839"
27,28,"""Perfect""[54]",Ed Sheeran,"November 9, 2017","2,974,982,274"
28,29,"""Waka Waka (This Time for Africa)""[55]",Shakira,"June 4, 2010","2,962,613,841"
29,30,"""Hello""[56]",Adele,"October 23, 2015","2,889,107,727"

Q2. Scrape the details team India’s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.
You need to find following details:

A) Match title (I.e. 1
st ODI)

B) Series

C) Place

D) Date

E) Time

Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [4]:
driver=driver = webdriver.Chrome(r'C:\Users\hp\Downloads\chromedriver_win32\chromedriver.exe')

time.sleep(2)
url = "https://www.bcci.tv/"
driver.get(url)

time.sleep(2)
fixtures=driver.find_element_by_xpath("//div[@class='navigation__drop-down drop-down drop-down--reveal-on-hover']/div/ul/li/a")
try:
    fixtures.click()
except ElementNotInteractableException:
    driver.get(fixtures.get_attribute('href'))
    

time.sleep(2) 
urls=[]
match_page=driver.find_elements_by_xpath("//div[@class='js-list']/a")  
for i in match_page:
    urls.append(i.get_attribute('href'))
  
    
time.sleep(1)   
match=[] 
series=[]
place=[]
date=[]
Time=[]
all_text = []
venue = []


for i in urls:
    driver.get(i)
    
    time.sleep(2)
    try:                    
        match_title=driver.find_element_by_xpath("//p[@class='mc-header-info__match-description']/span")
        match.append(match_title.text)
    except NoSuchElementException:
        match.append('No details available')
    
    time.sleep(2) 
    try:
        series_title=driver.find_element_by_xpath("//h1[@class='mc-header-info__title']/strong")
        series.append(series_title.text)
    except NoSuchElementException:
        series.append("No details Available")
    
    time.sleep(2)
    try:
        date_title=driver.find_element_by_xpath("//div[@class='mc-header-scorebox__datetime']/strong")
        date.append(date_title.text)
    except NoSuchElementException:
        date.append("No details Available")      
    
    time.sleep(2)   
    try:
        time_title=driver.find_element_by_xpath("//div[@class='mc-header-scorebox__datetime']/span")
        Time.append(time_title.text)
    except NoSuchElementException:
        Time.append("No details Available")    
      
    time.sleep(2)  
    try:
        place_title=driver.find_element_by_xpath("//h1[@class='mc-header-info__title']")
        venue.append(place_title.text)
    except NoSuchElementException:
        place.append("No details Available")
        
    
for i in venue:
    all_text.append(i.split())
for i in all_text:
    place.append(i[-1::]) 
    
time.sleep(2)       
df=pd.DataFrame({"Match":match,
                "Series":series,
                "Place":place,
                "Date":date,
                "Time":Time})
df

<ipython-input-4-db0c012d38ce>:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=driver = webdriver.Chrome(r'C:\Users\hp\Downloads\chromedriver_win32\chromedriver.exe')
C:\Users\hp\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py:483: UserWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  warnings.warn("find_element_by_* commands are deprecated. Please use find_element() instead")
C:\Users\hp\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py:502: UserWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  warnings.warn("find_elements_by_* commands are deprecated. Please use find_elements() instead")

,Match,Series,Place,Date,Time
0,MATCH 16,India v Pakistan,[Dubai],Sunday 24 October,19:30 IST
1,MATCH 28,India v New Zealand,[Dubai],Sunday 31 October,19:30 IST
2,MATCH 33,India v Afghanistan,[Dhabi],Wednesday 3 November,19:30 IST
3,MATCH 37,India v B1,[Dubai],Friday 5 November,19:30 IST
4,MATCH 42,India v A2,[Dubai],Monday 8 November,19:30 IST
5,1ST T20I,India v New Zealand,[Jaipur],Wednesday 17 November,19:00 IST
6,2ND T20I,India v New Zealand,[Ranchi],Friday 19 November,19:00 IST
7,3RD T20I,India v New Zealand,[Kolkata],Sunday 21 November,19:00 IST
8,1ST TEST,India v New Zealand,[Kanpur],Thursday 25 November,09:30 IST
9,2ND TEST,India v New Zealand,[Mumbai],Friday 3 December,09:30 IST
10,1ST TEST,South Africa v India,[Johannesburg],Friday 17 December,13:30 IST
11,2ND TEST,South Africa v India,[Centurion],Sunday 26 December,13:30 IST
12,3RD TEST,South Africa v India,[Johannesburg],Monday 3 January,13:30 IST
13,1ST ODI,South Africa v India,[Paarl],Tuesday 11 January,14:00 IST
14,2ND ODI,South Africa v India,[Town],Friday 14 January,14:00 IST
15,3RD ODI,South Africa v India,[Town],Sunday 16 January,14:00 IST
16,1ST T20I,South Africa v India,[Town],Wednesday 19 January,19:30 IST
17,2ND T20I,South Africa v India,[Town],Friday 21 January,19:30 IST
18,3RD T20I,South Africa v India,[Paarl],Sunday 23 January,19:30 IST
19,4TH T20I,South Africa v India,[Paarl],Wednesday 26 January,19:30 IST

Q3. Scrape the details of selenium exception from guru99.com.
Url = https://www.guru99.com/
You need to find following details:

A) Name

B) Description

Note: - From guru99 home page you have to reach to selenium exception handling page through code.

In [7]:
driver=driver = webdriver.Chrome(r'C:\Users\hp\Downloads\chromedriver_win32\chromedriver.exe')
time.sleep(2)

url = "https://www.guru99.com/"
driver.get(url)
time.sleep(2)


selenium_link=driver.find_element_by_xpath("//li[@class='g-menu-item g-menu-item-type-component g-menu-item-121  ']/a")
try:
    selenium_link.click()
except ElementNotInteractableException:
    driver.get(selenium_link.get_attribute('href'))
time.sleep(2)

exception_handle_link=driver.find_element_by_xpath("//a[@title='Selenium Exception Handling (Common Exceptions List)']")
try:
    exception_handle_link.click()
except ElementNotInteractableException:
    driver.get(exception_handle_link.get_attribute('href'))              
time.sleep(2)    
    
name=[]
try:
    names=driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/tr/td[1]")
    for i in names[1:]:
        name.append(i.text)
except NoSuchElementException:
    name.append('No details available')
time.sleep(2)   

desc=[]
try:
    desc_list=driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/tr/td[2]")
    for i in desc_list[1:]:
        desc.append(i.text)
except NoSuchElementException:
    desc.append('No details available')
time.sleep(2)

df=pd.DataFrame({"Exception_name":name,
                "Description":desc})
df

,Exception_name,Description
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command can't be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does n't sen...

Q4. Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/
You have to find following details:

A) Rank

B) State

C) GSDP at current price (19-20)

D) GSDP at current price (18-19)

E) Share(18-19)

F) GDP($ billion)

Note: - From statisticstimes home page you have to reach to economy page through code.

In [5]:
driver=driver = webdriver.Chrome(r'C:\Users\hp\Downloads\chromedriver_win32\chromedriver.exe')
time.sleep(2)

url = "http://statisticstimes.com/"
driver.get(url)
time.sleep(2)

economy=driver.find_element_by_xpath("//div[@class='dropdown'][2]/div/a[3]")
try:
    economy.click()
except ElementNotInteractableException:
    driver.get(economy.get_attribute('href'))
time.sleep(2)


indian_states=driver.find_element_by_xpath("//ul[@style='list-style-type:none;margin-left:20px;']//li[1]/a")

try:
    indian_states.click()
except ElementNotInteractableException:
    driver.get(indian_states.get_attribute('href')) 
time.sleep(2)


rank=[]
try:
    ranks=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[1]")
    for i in ranks:
        rank.append(i.text)
except NoSuchElementException:
    rank.append('No details available')
time.sleep(2)


State=[]
try:
    states=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[2]")
    for i in states:
        State.append(i.text)
except NoSuchElementException:
    State.append('No details available')
time.sleep(2)


GSDP_20=[]
try:
    info=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[3]")
    for i in info:
        GSDP_20.append(i.text)
except NoSuchElementException:
    GSDP_20.append('No details available')
time.sleep(2)    
    
GSDP_19=[]
try:
    info=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[4]")
    for i in info:
        GSDP_19.append(i.text)
except NoSuchElementException:
    GSDP_19.append('No details available')
time.sleep(2)

share=[]
try:
    info=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[5]")
    for i in info:
        share.append(i.text)
except NoSuchElementException:
    share.append('No details available')
time.sleep(2)

GDP_billion=[]
try:
    info=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[6]")
    for i in info:
        GDP_billion.append(i.text)
except NoSuchElementException:
    GDP_billion.append('No details available')
time.sleep(2)

df=pd.DataFrame({'Rank':rank,
                'State':State,
                'GSDP(19-20)':GSDP_20,
                'GSDP(18-19)':GSDP_19,
                'Share(18-19)':share,
                'GDP(Billion_$)':GDP_billion})
df

<ipython-input-5-8997b14b40ce>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=driver = webdriver.Chrome(r'C:\Users\hp\Downloads\chromedriver_win32\chromedriver.exe')
C:\Users\hp\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py:483: UserWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  warnings.warn("find_element_by_* commands are deprecated. Please use find_element() instead")
C:\Users\hp\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py:502: UserWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  warnings.warn("find_elements_by_* commands are deprecated. Please use find_elements() instead")

,Rank,State,GSDP(19-20),GSDP(18-19),Share(18-19),GDP(Billion_$)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
8,9,Telangana,"969,604","861,031",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
10,11,Kerala,-,"781,653",4.14%,118.733
11,12,Delhi,"856,112","774,870",4.10%,117.703
12,13,Haryana,"831,610","734,163",3.89%,111.519
13,14,Bihar,"611,804","530,363",2.81%,80.562
14,15,Punjab,"574,760","526,376",2.79%,79.957
15,16,Odisha,"521,275","487,805",2.58%,74.098
16,17,Assam,-,"315,881",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
18,19,Jharkhand,"328,598","297,204",1.57%,45.145
19,20,Uttarakhand,-,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
22,23,Goa,"80,449","73,170",0.39%,11.115
23,24,Tripura,"55,984","49,845",0.26%,7.571
24,25,Chandigarh,-,"42,114",0.22%,6.397
25,26,Puducherry,"38,253","34,433",0.18%,5.230
26,27,Meghalaya,"36,572","33,481",0.18%,5.086
27,28,Sikkim,"32,496","28,723",0.15%,4.363
28,29,Manipur,"31,790","27,870",0.15%,4.233
29,30,Nagaland,-,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
31,32,Mizoram,"26,503","22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

Q5. Scrape the details of trending repositories on Github.com.
Url = https://github.com/
You have to find the following details:

A) Repository title

B) Repository description

C) Contributors count

D) Language used

Note: - From the home page you have to click on the trending option from Explore menu through code.

In [16]:
driver=driver = webdriver.Chrome(r'C:\Users\hp\Downloads\chromedriver_win32\chromedriver.exe')
time.sleep(2)


url = "https://github.com/"
driver.get(url)
time.sleep(3)


explore=driver.find_element_by_xpath("//button[@class='btn-link d-lg-none mt-1 js-details-target']")
explore.click()
time.sleep(2)

explore=driver.find_element_by_xpath("//ul[@class='list-style-none mb-3']/li[3]/a")
try:
    explore.click()
except:
    driver.get(explore.get_attribute('href'))
time.sleep(2)

  
repo_urls=[]
Contributors_count=[]
Language_used=[]
repo_title=[]
repo_desc=[]

repos=driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a")
for i in repos:
    repo_urls.append(i.get_attribute('href'))
time.sleep(2) 

    
repo_title=[]
try:
    repos=driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']")
    for i in repos:
        repo_title.append(i.text)
except NoSuchElementException:
    repo_title.append('No details available')
time.sleep(3)
    

for i in repo_urls:
    driver.get(i)
    l=[]
    time.sleep(3)
    try:
        repo = driver.find_element_by_xpath("/html/body/div[4]/div/main/div[2]/div/div/div[2]/div[2]/div/div[1]/div/p")
        repo_desc.append(repo.text)
    except NoSuchElementException:
        repo_desc.append('-')
    
    try:
        count=driver.find_element_by_xpath("//h2[@class='h4 mb-3']/a[contains(text(),'Contributors')]/span")
        Contributors_count.append(count.text)
    except NoSuchElementException:
        Contributors_count.append('No details available')
    time.sleep(2)
      
    languages=driver.find_elements_by_xpath("//li[@class='d-inline']//a//span[1]")
    if languages:    
        for i in languages:
            l.append(i.text)
    else:
        l.append('No languages used')
    Language_used.append(l)   
    
time.sleep(2)   
df=pd.DataFrame({'Title':repo_title,
                'Description':repo_desc,
                'Contributors_count':Contributors_count,
                'Language_used':Language_used})
df

,Title,Description,Contributors_count,Language_used
0,YMFE / yapi,YApi 是一个可本地部署的、打通前后端及QA的、可视化的接口管理平台,63,"[JavaScript, SCSS]"
1,SmartKeyerror / Psyduck,"Record CS knowlegement with XMind, version 2.0...",No details available,"[Go, C++, C]"
2,returntocorp / semgrep,Lightweight static analysis for many languages...,49,"[Java, OCaml, JavaScript, Python, Standard ML,..."
3,laynH / Anime-Girls-Holding-Programming-Books,Anime Girls Holding Programming Books,117,[No languages used]
4,danistefanovic / build-your-own-x,🤓 Build your own (insert technology here),70,[No languages used]
5,catchorg / Catch2,"A modern, C++-native, header-only, test framew...",264,"[C++, CMake, Python, Shell, Batchfile, PowerSh..."
6,EbookFoundation / free-programming-books,📚 Freely available programming books,"1,626",[No languages used]
7,swisskyrepo / PayloadsAllTheThings,A list of useful payloads and bypass for Web A...,152,"[Python, Ruby, ASP.NET, Classic ASP, PHP, Jupy..."
8,ankurchavda / SparkLearning,A comprehensive Spark guide collated from mult...,No details available,[No languages used]
9,goldbergyoni / nodebestpractices,✅ The Node.js best practices list (June 2021),196,"[JavaScript, Shell, Dockerfile, CSS, HTML, Typ..."
10,Gaboros / VenturePlan,-,6,"[Lua, Java]"
11,sorrycc / awesome-javascript,🐢 A collection of awesome browser-side JavaScr...,266,[No languages used]
12,kean / Pulse,Logger and network inspector for Apple platforms,5,"[Swift, Shell]"
13,o3de / o3de,Source for fully featured AAA Open 3D Engine,108,"[C++, Python, CMake, C, Lua, Objective-C++]"
14,ruanyf / weekly,科技爱好者周刊，每周五发布,25,[No languages used]
15,shufflewzc / faker2,不知名大佬备份,No details available,"[JavaScript, Python]"
16,spring-projects / spring-graphql,Spring integration for GraphQL,10,"[Java, CSS, Shell]"
17,chefyuan / algorithm-base,专门为刚开始刷题的同学准备的算法基地，没有最细只有更细，立志用动画将晦涩难懂的算法说的通俗易懂！,5,[Java]
18,star261 / jd,-,2,[JavaScript]
19,microsoft / vscode,Visual Studio Code,"1,447","[TypeScript, JavaScript, CSS, Inno Setup, HTML..."
20,puppeteer / puppeteer,Headless Chrome Node.js API,348,"[TypeScript, JavaScript, HTML]"
21,zero205 / JD_tencent_scf,京东腾讯云函数版，低调使用，不要fork！！,42,"[JavaScript, Python]"
22,ClickHouse / ClickHouse,ClickHouse® is a free analytics DBMS for big data,723,"[C++, Python, Assembly, Shell, CMake, JavaScript]"
23,madMAx43v3r / chia-plotter,-,33,"[C, C++]"
24,emqx / emqx,"An Open-Source, Cloud-Native, distributed MQTT...",64,"[Erlang, Shell, C, Makefile, Batchfile, Python]"

Q6. Scrape the details of top 100 songs on billboard.com.
Url = https://www.billboard.com/
You have to find the following details:

A) Song name

B) Artist name

C) Last week rank

D) Peak rank

E) Weeks on board

Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [6]:
driver=driver = webdriver.Chrome(r'C:\Users\hp\Downloads\chromedriver_win32\chromedriver.exe')
time.sleep(2)

url = "https://www.billboard.com/"
driver.get(url)
time.sleep(2)


charts=driver.find_element_by_xpath("//ul[@class='header__subnav__list display--flex flex--left-center flex-md--center-center']//li[3]//a")
try:
    charts.click()
except ElementNotInteractableException:
    driver.get(charts.get_attribute('href'))
time.sleep(2)


song_name=[]
try:
    names=driver.find_elements_by_xpath("//span[@class='chart-element__information__song text--truncate color--primary']")
    for i in names:
        song_name.append(i.text)
except NoSuchElementException:
    song_name.append('No details available')
time.sleep(2)    


artist_name=[]
try:
    names=driver.find_elements_by_xpath("//span[@class='chart-element__information__artist text--truncate color--secondary']")
    for i in names:
        artist_name.append(i.text)
except NoSuchElementException:
    artist_name.append('No details available')
time.sleep(2)
    

last_week_rank=[]
try:
    ranks=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--last']")
    for i in ranks:
        last_week_rank.append(i.text)
except NoSuchElementException:
    last_week_rank.append('No details available') 
time.sleep(2)

peak_rank=[]
try:
    ranks=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--peak']")
    for i in ranks:
        peak_rank.append(i.text)
except NoSuchElementException:
    peak_rank.append('No details available')
time.sleep(2)

weeks=[]
try:
    week_count=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--week']")
    for i in week_count:
        weeks.append(i.text)
except NoSuchElementException:
    weeks.append('No details available')
time.sleep(2)


df=pd.DataFrame({'Song_Name':song_name,
                'Artist_Name':artist_name,
                'Last_week_rank':last_week_rank,
                'Peak':peak_rank,
                'Weeks_on_chart':weeks})
df

<ipython-input-6-e41a79b0fb9f>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=driver = webdriver.Chrome(r'C:\Users\hp\Downloads\chromedriver_win32\chromedriver.exe')
C:\Users\hp\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py:483: UserWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  warnings.warn("find_element_by_* commands are deprecated. Please use find_element() instead")
C:\Users\hp\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py:502: UserWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  warnings.warn("find_elements_by_* commands are deprecated. Please use find_elements() instead")

,Song_Name,Artist_Name,Last_week_rank,Peak,Weeks_on_chart
0,My Universe,Coldplay x BTS,-,1,1
1,Stay,The Kid LAROI & Justin Bieber,1,1,12
2,Industry Baby,Lil Nas X & Jack Harlow,2,2,10
3,Way 2 Sexy,Drake Featuring Future & Young Thug,3,1,4
4,Fancy Like,Walker Hayes,5,5,15
...,...,...,...,...,...
95,Pipe Down,Drake,68,14,4
96,Papi's Home,Drake,66,8,4
97,Chosen,Blxst & Tyga Featuring Ty Dolla $ign,-,98,1
98,Toxic Punk,YoungBoy Never Broke Again,-,99,1
99,Moon,Kanye West,76,17,5

Q7. Scrape the details of Data science recruiters from naukri.com.
Url = https://www.naukri.com/
You have to find the following details:

A) Name

B) Designation

C) Company

D) Skills they hire for

E) Location

Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and
click on search. All this should be done through code

In [7]:
driver=driver = webdriver.Chrome(r'C:\Users\hp\Downloads\chromedriver_win32\chromedriver.exe')
time.sleep(2)

url = "https://www.naukri.com/"
driver.get(url)
time.sleep(2)

recruiters=driver.find_element_by_xpath("//a[@title='Search Recruiters']")
driver.get(recruiters.get_attribute('href'))
time.sleep(1)

search=driver.find_element_by_xpath("//input[@class='sugInp']")
search.send_keys("Data Science")
time.sleep(1)

button=driver.find_element_by_xpath("//button[@id='qsbFormBtn']")
button.click()
time.sleep(1)

name=[]
try:
    names=driver.find_elements_by_xpath("//div[@class='recInfo']/div/p/a[1]")
    for i in names:
        name.append(i.text)
except NoSuchElementException:
    name.append('No details available')
time.sleep(2)


designation=[]
try:
    designation_list=driver.find_elements_by_xpath("//div[@class='recInfo']/div/p/span[1]")
    for i in designation_list:
        designation.append(i.text)
except NoSuchElementException:
    designation.append('No details available')
time.sleep(2)


company=[]
try:
    companies=driver.find_elements_by_xpath("//div[@class='recInfo']/div/p/a[2]")
    for i in companies:
        company.append(i.text)
except NoSuchElementException:
    company.append('No details available')
time.sleep(2)

location=[]
soup=BeautifulSoup(driver.page_source,'html.parser')
l=soup.find_all('div',attrs={'vcard'})
for i in l:
    try:
        location.append(i.find('small').text)
    except AttributeError :
        location.append("No details available")
time.sleep(2)

skill=[]
try:
    skills=driver.find_elements_by_xpath("//div[@class='recInfo']/div[2]")
    for i in skills:
        skill.append(i.text)
except NoSuchElementException:
    skill.append('No details available')
time.sleep(2)    
        
df=pd.DataFrame({'Name':name,
                'Designation':designation,
                'Company':company,
                "Location":location,
                'Skills I hire':skill})
df

<ipython-input-7-55863d39e753>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=driver = webdriver.Chrome(r'C:\Users\hp\Downloads\chromedriver_win32\chromedriver.exe')
C:\Users\hp\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py:483: UserWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  warnings.warn("find_element_by_* commands are deprecated. Please use find_element() instead")
C:\Users\hp\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py:502: UserWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  warnings.warn("find_elements_by_* commands are deprecated. Please use find_elements() instead")

,Name,Designation,Company,Location,Skills I hire
0,Aakash Harit,HR Manager,Data Science Network,Delhi,"Classic ASP Developer, Internet Marketing Prof..."
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,Hyderabad / Secunderabad,".Net, Java, Data Science, Linux Administration..."
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,Pune,"Data Science, Artificial Intelligence, Machine..."
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,Ahmedabad,"Mean Stack, javascript, angularjs, mongodb, We..."
4,Narasimha,Company Recruiter,Step Next Private Limited,Hyderabad / Secunderabad,"Data Modeling, Data Wrangling, seaborn, eda, p..."
5,subhas patel,Founder CEO,LibraryXProject,UK - (london),"Hadoop, Spark, Digital Strategy, Data Architec..."
6,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,Vadodara / Baroda,"Analytics, Business Intelligence, Business Ana..."
7,Institute for Financial Management and Resear,Programme Manager,IFMR,Chennai,Data Science
8,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,Trivandrum,"Machine Learning, algorithms, Go Getter, Compu..."
9,Asif Lucknowi,Director,Weupskill- Live Wire India,Indore,"Technical Training, Software Development, Pres..."
10,InstaFinancials,Human Resource,CBL Data Science Private Limited,Bengaluru / Bangalore,"Software Development, It Sales, Account Manage..."
11,Priyanka Akiri,HR Manager,Infinitive Software Solutions Pvt.Ltd.,Hyderabad,"Oracle Dba, Data Science, Data Warehousing, ET..."
12,Kalpana Dumpala,Executive Hiring,Innominds Software,Hyderabad / Secunderabad,"Qa, Ui/ux, Java Developer, Java Architect, C++..."
13,Mubarak,Company HR,MoneyTap,Bengaluru / Bangalore,"Business Intelligence, Data Warehousing, Data ..."
14,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,Mumbai,"Office Administration, Hr Administration, tele..."
15,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,Pune,"Qlikview, Qlik Sense, Microsoft Azure, Power B..."
16,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,Hyderabad / Secunderabad,"Social Media, digital media maketing, seo, smm..."
17,Kapil Devang,HR Manager,BISP Solutions,Bhopal,"Big Data, Hadoop, Data Analytics, Data Science"
18,Manisha Yadav,HR Executive,Easi Tax,Navi Mumbai,"Telecalling, Client Interaction, Marketing, Re..."
19,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Cochin,Data Science
20,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,Delhi,"Corporate Sales, Software Development, Softwar..."
21,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,Hyderabad / Secunderabad,"Data Analytics, Data Science, Machine Learning..."
22,Rithika dadwal,HR Recruiter,Affine Analytics,Pune,"Data Science, Machine Learning, Python, R, Dee..."
23,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,Pune,"Big Data, Data Science, Artificial Intelligenc..."
24,Shaun Rao,Manager Human Resources,Exela Technologies,Pune,"Java, Net, Angularjs, Hr, Infrastructure, Mana..."
25,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,Pune,"Data Science, Artificial Intelligence, Machine..."
26,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,Bengaluru / Bangalore,"Software Architecture, Vp Engineering, Product..."
27,kumar,Proprietor,trainin,Bengaluru / Bangalore,"Data Science, Hadoop, Rpas, Devops, Python, Aw..."
28,Sunil Vedula,CEO,Nanoprecise Sci Corp,No details available,"Signal Processing, Machine Learning, Neural Ne..."
29,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,Delhi,"Web Technologies, Project Management, Software..."
30,Priya Khare,Senior Manager,Independent Consultant,Bengaluru / Bangalore,"Data Science, Artificial Intelligence, analyti..."
31,Dhruv Dev Dubey,Company Recruitment Head,Confidential,Bengaluru / Bangalore,"Server Administartion, Verilog, Vhdl, Digital ..."
32,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd",Mysoru / Mysore,"Data Analytics, Managed Services, Team Leading..."
33,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,Hyderabad / Secunderabad,"Data Science, Machine Learning, Big Data Analy..."
34,Ravi Dubey,Recruitment Manager,HyrEzy Talent Solutions LLP,Ghaziabad,Walmart Interra Skeps Expressstores indifi whi...
35,Radha Manivasagam,HR Executive,Techcovery,Bengaluru / Bangalore,"Python, Artificial Intelligence, Machine Learn..."
36,Prateek Kumar,Head,Trisect,Noida,"Java, Python, Angularjs, Software Testing, Mac..."
37,Amit Sharma,Consultant,ASCO consulting,New Delhi,"Machine Learning, Artificial Intelligence, Dat..."
38,Kanan,senior technology instructor,NY INST,Chennai,"C, C++, Artificial Intelligence, Python, Php, ..."
39,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,Aligarh,"Relationship Management, Retail Sales, Private..."
40,Brad,"Manager, Technical Recruiting",O.C. Tanner,Salt Lake City,"Data Science, Software Engineering"
41,Rutuja Pawar,Technical Recruiter,Demand Matrix,Pune,"Data Science, Big Data Analytics, Digital Mark..."
42,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,Bengaluru / Bangalore,"Data Science, Recruitment, Salary"
43,Ankit Sinha,Head Analytics,Suntech Global,Mumbai,"B.Tech, Tableau, Statistics, R, Analytics, Tim..."
44,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,Indore,"Software Development, Business Intelligence, B..."
45,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,Bengaluru / Bangalore,"Data Science, Node.js, Angularjs"
46,Ashwini,Director Global Delivery,MRP Advisers,MYSORE,"Data Science, Media Marketing, Resource Planni..."
47,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,Hyderabad / Secunderabad,"Data Analysis, Learning, Data Science, Compute..."
48,Rajani Nagaraj,HR Manager,WildJasmine,Bengaluru / Bangalore,"Java, Hadoop, R, Machine Learning, Spark, Flum..."
49,ROHIT Kumar,Architect,LNT Private Limited,Mumbai,"Software Development, Core Java, Unit Testing,..."

Q8. Scrape the details of Highest selling novels.
Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/
You have to find the following details:

A) Book name

B) Author name

C) Volumes sold

D) Publisher

E) Genre

In [8]:
driver=driver = webdriver.Chrome(r'C:\Users\hp\Downloads\chromedriver_win32\chromedriver.exe')
time.sleep(2)

url = "https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare"
driver.get(url)
time.sleep(2)

book_name=[]
try:
    names=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[2]")
    for i in names:
        book_name.append(i.text)
except NoSuchElementException:
    book_name.append('No details available')
time.sleep(2)

author_name=[]
try:
    names=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[3]")
    for i in names:
        author_name.append(i.text)
except NoSuchElementException:
    author_name.append('No details available')
time.sleep(2)


Sale=[]
try:
    sale=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[4]")
    for i in sale:
        Sale.append(i.text)
except NoSuchElementException:
    Sale.append('No details available')
time.sleep(2)    

publisher=[]
try:
    publishers=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[5]")
    for i in publishers:
        publisher.append(i.text)
except NoSuchElementException:
    publisher.append('No details available')
time.sleep(2)

genre=[]
try:
    genres=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[6]")
    for i in genres:
        genre.append(i.text)
except NoSuchElementException:
    genre.append('No details available')
time.sleep(2)

df=pd.DataFrame({"Book_name":book_name,
                "Author_name":author_name,
                'Volume sold':Sale,
                'Publisher':publisher,
                'Genre':genre})
df

<ipython-input-8-1a9968ee5dd1>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=driver = webdriver.Chrome(r'C:\Users\hp\Downloads\chromedriver_win32\chromedriver.exe')
C:\Users\hp\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py:502: UserWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  warnings.warn("find_elements_by_* commands are deprecated. Please use find_elements() instead")

,Book_name,Author_name,Volume sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

Q9. Scrape the details most watched tv series of all time from imdb.com.
Url = https://www.imdb.com/list/ls095964455/
You have to find the following details:

A) Name

B) Year span

C) Genre

D) Run time

E) Ratings

F) Votes

In [9]:
driver=driver = webdriver.Chrome(r'C:\Users\hp\Downloads\chromedriver_win32\chromedriver.exe')
time.sleep(2)

url = "https://www.imdb.com/list/ls095964455"
driver.get(url)
time.sleep(2)

name=[]
try:
    names=driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a")
    for i in names:
        name.append(i.text)
except NosuchElementException:
    name.append('No details available')
time.sleep(2)


years=[]
try:
    span=driver.find_elements_by_xpath("//h3[@class='lister-item-header']/span[2]")
    for i in span:
        years.append(i.text)
except NosuchElementException:
    years.append('No details available')
time.sleep(2)


genre=[]
try:
    genres=driver.find_elements_by_xpath("//span[@class='genre']")
    for i in genres:
        genre.append(i.text)
except NoSuchElementException:
    genre.append('No details available')
time.sleep(2)


run_time=[]
try:
    info=driver.find_elements_by_xpath("//span[@class='runtime']")
    for i in info:
        run_time.append(i.text)
except NoSuchElementException:
    run_time.append('No details available')
time.sleep(2)


rating=[]
try:
    info=driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']/span[2]")
    for i in info:
        rating.append(i.text)
except NoSuchElementException:
    rating.append('No details available')
time.sleep(2)

votes=[]
try:
    info=driver.find_elements_by_xpath("//span[@name='nv']")
    for i in info:
        votes.append(i.text)
except NoSuchElementException:
    votes.append('No details available')
time.sleep(2)


df=pd.DataFrame({"Name":name,
                "years":years,
                "Genre":genre,
                "Run_time":run_time,
                "Rating":rating,
                "Votes":votes})
df

<ipython-input-9-4ffab243ba60>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=driver = webdriver.Chrome(r'C:\Users\hp\Downloads\chromedriver_win32\chromedriver.exe')
C:\Users\hp\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py:502: UserWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  warnings.warn("find_elements_by_* commands are deprecated. Please use find_elements() instead")

,Name,years,Genre,Run_time,Rating,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,882,733"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"916,101"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"904,457"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"270,948"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"231,326"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"45,903"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"56,775"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"177,368"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"36,893"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"203,801"

Q10. Details of Datasets from UCI machine learning repositories.
 Url = https://archive.ics.uci.edu/
 You have to find the following details:
 
A) Dataset name

B) Data type

C) Task

D) Attribute type

E) No of instances

F) No of attribute

G) Year

Note: - from the home page you have to go to the ShowAllDataset page through code

In [10]:
driver=driver = webdriver.Chrome(r'C:\Users\hp\Downloads\chromedriver_win32\chromedriver.exe')
time.sleep(2)

url = "https://archive.ics.uci.edu/"
driver.get(url)
time.sleep(2)

show=driver.find_element_by_xpath("//a[@href='datasets.php']")
show.click()
time.sleep(1)


name=[]
try:
    names=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[1]/table/tbody/tr/td[2]/p/b/a")
    for i in names:
        name.append(i.text)
except NoSuchElementException:
    name.append('No details available')
time.sleep(2)

data_type=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]")
    for i in info[1:]:
         data_type.append(i.text)
except NoSuchElementException:
    data_type.append("No information")
time.sleep(2)


default_task=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]")
    for i in info[1:]:
         default_task.append(i.text)
except NoSuchElementException:
    default_task.append("No information")
time.sleep(2)


attr_type=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]")
    for i in info[1:]:
         attr_type.append(i.text)
except NoSuchElementException:
    attr_type.append("No information")
time.sleep(2)


no_of_instances=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]")
    for i in info[1:]:
         no_of_instances.append(i.text)
except NoSuchElementException:
    no_of_instances.append("No information")
time.sleep(2)


no_of_attributes=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]")
    for i in info[1:]:
         no_of_attributes.append(i.text)
except NoSuchElementException:
    no_of_attributes.append("No information")
time.sleep(2)


year=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]")
    for i in info[1:]:
         year.append(i.text)
except NoSuchElementException:
    year.append("No information")
time.sleep(2)

df=pd.DataFrame({'Name':name,
                'Data_type':data_type,
                'Task':default_task,
                'Attribute_type':attr_type,
                'No_of_instances':no_of_instances,
                'No_of_attributes':no_of_attributes,
                'Year':year})
df

<ipython-input-10-814498e641da>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=driver = webdriver.Chrome(r'C:\Users\hp\Downloads\chromedriver_win32\chromedriver.exe')
C:\Users\hp\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py:483: UserWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  warnings.warn("find_element_by_* commands are deprecated. Please use find_element() instead")
C:\Users\hp\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py:502: UserWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  warnings.warn("find_elements_by_* commands are deprecated. Please use find_elements() instead")

,Name,Data_type,Task,Attribute_type,No_of_instances,No_of_attributes,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
583,in-vehicle coupon recommendation,Multivariate,Classification,,12684,23,2020
584,Gait Classification,Multivariate,Classification,Real,48,321,2020
585,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
586,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
587,Synchronous Machine Data Set,Multivariate,Regression,Real,557,5,2021